name: CML-EC2-Runner-GPU
on: 
  workflow_dispatch:

jobs:
  # Previous jobs remain the same...

  train-and-report:
    runs-on: [self-hosted, cml-gpu]
    needs: launch-runner
    outputs:
      commit_id: ${{ steps.get_commit_id_ec2.outputs.commit_id }}
    timeout-minutes: 20
    steps:
      # Previous steps remain the same until DVC commands...

      - name: Run DVC commands in container
        run: |
          mkdir -p /home/ubuntu/emlo4-session-08-aws-session/model_storage
          docker run --gpus=all \
            -v "/home/ubuntu/emlo4-session-08-aws-session/model_storage:/home/ubuntu/emlo4-session-08-aws-session/model_storage" \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }} \
            ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest \
            /bin/bash -c "
              set -x  # Enable debug mode
              dvc pull -r myremote && \
              dvc repro -f && \
              # Ensure proper permissions
              chown -R $(id -u):$(id -g) /home/ubuntu/emlo4-session-08-aws-session/model_storage
            "

      - name: Fix Permissions
        run: |
          sudo chown -R $USER:$USER /home/ubuntu/emlo4-session-08-aws-session/model_storage
          sudo chmod -R 755 /home/ubuntu/emlo4-session-08-aws-session/model_storage

      - name: Debug - List contents
        run: |
          echo "Current directory contents:"
          ls -la
          echo "\nFull path contents:"
          sudo ls -la /home/ubuntu/emlo4-session-08-aws-session/model_storage/
          echo "\nChecking file existence:"
          if [ -f "/home/ubuntu/emlo4-session-08-aws-session/model_storage/epoch-checkpoint.ckpt" ]; then
            echo "File exists"
            stat /home/ubuntu/emlo4-session-08-aws-session/model_storage/epoch-checkpoint.ckpt
          else
            echo "File does not exist"
            ls -la /home/ubuntu/emlo4-session-08-aws-session/
          fi

      - name: Set checkpoint path
        id: set_checkpoint
        run: |
          if [ -f "/home/ubuntu/emlo4-session-08-aws-session/model_storage/epoch-checkpoint.ckpt" ]; then
            echo "CHECKPOINT_FILE=/home/ubuntu/emlo4-session-08-aws-session/model_storage/epoch-checkpoint.ckpt" >> $GITHUB_ENV
            echo "Found checkpoint file: epoch-checkpoint.ckpt"
          else
            echo "Error: Checkpoint file not found"
            # Add debugging information
            echo "Directory contents:"
            sudo ls -la /home/ubuntu/emlo4-session-08-aws-session/model_storage/
            exit 1
          fi

      - name: Upload checkpoint to S3
        run: |
          checkpoint_path="/home/ubuntu/emlo4-session-08-aws-session/model_storage/epoch-checkpoint.ckpt"
          bucket_name="mybucket-emlo-mumbai"
          s3_key="session-08-checkpoint/${{ needs.launch-runner.outputs.commit_id }}/epoch-checkpoint.ckpt"
          echo "Uploading $checkpoint_path to s3://$bucket_name/$s3_key"
          if [ -f "$checkpoint_path" ]; then
            sudo aws s3 cp "$checkpoint_path" "s3://$bucket_name/$s3_key"
          else
            echo "Error: Checkpoint file not found at $checkpoint_path"
            # Add debugging information
            echo "Directory contents:"
            sudo ls -la /home/ubuntu/emlo4-session-08-aws-session/model_storage/
            exit 1
          fi
