name: CML-EC2-Runner
on: 
  workflow_dispatch:

jobs:
  build-and-push-ecr-image:
    name: Build and push ECR image
    runs-on: ubuntu-latest
    outputs:
      commit_id: ${{ steps.get_commit_id.outputs.commit_id }}
      image_uri: ${{ steps.build-image.outputs.image_uri }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Public ECR requires us-east-1

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      - name: Get latest commit ID
        id: get_commit_id
        run: |
          latest_commit=$(git rev-parse HEAD)
          echo "commit_id=$latest_commit" >> $GITHUB_OUTPUT

      - name: Build, tag, and push image to Amazon ECR Public
        id: build-image
        env:
          ECR_REGISTRY: public.ecr.aws
          ECR_NAMESPACE: y6b4w2a2
          ECR_REPOSITORY: aws-session/aws-session-ecr
          IMAGE_TAG: ${{ steps.get_commit_id.outputs.commit_id }}
        run: |
          # Build with both latest and commit-specific tags
          FULL_IMAGE_URI=$ECR_REGISTRY/$ECR_NAMESPACE/$ECR_REPOSITORY
          docker build -t $FULL_IMAGE_URI:$IMAGE_TAG -t $FULL_IMAGE_URI:latest .
          docker push $FULL_IMAGE_URI:$IMAGE_TAG
          docker push $FULL_IMAGE_URI:latest
          echo "image_uri=$FULL_IMAGE_URI:$IMAGE_TAG" >> $GITHUB_OUTPUT

  launch-runner:
    runs-on: ubuntu-latest
    needs: build-and-push-ecr-image
    outputs:
      commit_id: ${{ steps.get_commit_id_runner.outputs.commit_id }}
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v2

      - name: Get latest commit ID
        id: get_commit_id_runner
        run: |
          echo "commit_id=${{ needs.build-and-push-ecr-image.outputs.commit_id }}" >> $GITHUB_OUTPUT

      - name: Deploy runner on AWS EC2 
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cml runner launch \
          --cloud=aws \
          --name=session-08-${{ steps.get_commit_id_runner.outputs.commit_id }} \
          --cloud-region=ap-south-1 \
          --cloud-type=g4dn.xlarge \
          --cloud-hdd-size=64 \
          --cloud-spot \
          --single \
          --labels=cml-gpu \
          --idle-timeout=100 \
          --cloud-startup-script='
            sudo systemctl start docker && 
            sudo usermod -aG docker $(whoami) && 
            aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
          '

  train-and-report:
    runs-on: [self-hosted, cml-gpu]
    needs: [launch-runner, build-and-push-ecr-image]
    timeout-minutes: 20
    steps:
      - name: Verify Docker and GPU Setup
        run: |
          echo "Verifying Docker installation..."
          docker --version
          docker info
          
          echo "Verifying GPU setup..."
          nvidia-smi
          docker run --rm --gpus all nvidia/cuda:11.6.2-base-ubuntu20.04 nvidia-smi

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Pull and Run Training Container
        env:
          IMAGE_URI: ${{ needs.build-and-push-ecr-image.outputs.image_uri }}
        run: |
          mkdir -p model_storage
          docker run --gpus=all \
            -v "$(pwd)/model_storage:/workspace/model_storage" \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e AWS_DEFAULT_REGION=ap-south-1 \
            ${IMAGE_URI} \
            /bin/bash -c "
              dvc pull -r myremote && \
              mkdir -p model_storage && \
              dvc repro -f 
            "

      - name: Upload Model Checkpoint
        run: |
          if [ -f ./model_storage/best_model_checkpoint.txt ]; then
            checkpoint_file=$(head -n 1 ./model_storage/best_model_checkpoint.txt)
            bucket_name="mybucket-emlo-mumbai"
            s3_key="session-08-checkpoint/${{ needs.launch-runner.outputs.commit_id }}/$(basename "$checkpoint_file")"
            echo "Uploading $checkpoint_file to s3://$bucket_name/$s3_key"
            aws s3 cp "$checkpoint_file" "s3://$bucket_name/$s3_key"
          else
            echo "No checkpoint file found"
            exit 1
          fi

      - name: Cleanup
        if: always()
        run: |
          docker system prune -f
