- name: Run DVC commands in container
        run: |
          mkdir -p model_storage
          docker run --gpus=all \
            -v "$(pwd)/model_storage:/workspace/model_storage" \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }} \
            ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest \
            /bin/bash -c "
              set -x  # Enable debug mode
              dvc pull -r myremote && \
              mkdir -p model_storage && \
              dvc repro -f && \
              # Check for the specific checkpoint file
              if [ -f /workspace/model_storage/epoch-checkpoint.ckpt ]; then
                echo 'Found checkpoint file'
                ls -la /workspace/model_storage/epoch-checkpoint.ckpt
              else
                echo 'WARNING: Checkpoint file not found'
                echo 'Contents of model_storage:'
                ls -la /workspace/model_storage/
                exit 1
              fi
            "

      - name: Debug - List contents
        run: |
          echo "Current directory contents:"
          ls -la
          echo "\nmodel_storage directory contents:"
          ls -la model_storage/
          
      - name: Set checkpoint path
        id: set_checkpoint
        run: |
          if [ -f ./model_storage/epoch-checkpoint.ckpt ]; then
            echo "CHECKPOINT_FILE=./model_storage/epoch-checkpoint.ckpt" >> $GITHUB_ENV
            echo "Found checkpoint file: epoch-checkpoint.ckpt"
          else
            echo "Error: Checkpoint file not found"
            exit 1
          fi

      - name: Upload checkpoint to S3
        run: |
          checkpoint_path="./model_storage/epoch-checkpoint.ckpt"
          bucket_name="mybucket-emlo-mumbai"
          s3_key="session-08-checkpoint/${{ needs.launch-runner.outputs.commit_id }}/epoch-checkpoint.ckpt"
          echo "Uploading $checkpoint_path to s3://$bucket_name/$s3_key"
          if [ -f "$checkpoint_path" ]; then
            aws s3 cp "$checkpoint_path" "s3://$bucket_name/$s3_key"
          else
            echo "Error: Checkpoint file not found at $checkpoint_path"
            exit 1
          fi
